name: Run Non Follwers

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project ./src/Followers.Console/Followers.Console.csproj --configuration Release --no-build
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          INSTAGRAM_SETTINGS_COOKIE: ${{ secrets.INSTAGRAM_SETTINGS_COOKIE }}
          INSTAGRAM_SETTINGS_USER_ID: ${{ secrets.INSTAGRAM_SETTINGS_USER_ID }}
          INSTAGRAM_SETTINGS_IG_APP_ID: ${{ secrets.INSTAGRAM_SETTINGS_IG_APP_ID }}
